# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'c36c8c10-baa0-4872-969d-5579591bca1d'
  azureRgName: "met-api-rg"
  appName: "met-api-function-app"
  azureSubscriptionConnection: "ARMConnection"
  slot: "staging"

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: $(azureSubscriptionConnection)
    appType: "functionAppLinux"
    appName: $(appName)
    package: "$(System.DefaultWorkingDirectory)/**/*.zip"
    #package: $(System.ArtifactsDirectory)/**/*.zip (alternative)
    runtimeStack: "PYTHON|3.8"
    resourceGroupName: $(azureRgName)
    slotName: $(slot)
    