# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: true

pool:
  vmImage: "ubuntu-latest"

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'c36c8c10-baa0-4872-969d-5579591bca1d'
  azureRgName: "met-api-rg"
  appName: "met-api-function-app"
  azureSubscriptionConnection: "ARMConnection"
  slot: "staging"

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: $(azureSubscriptionConnection)
    appType: "functionAppLinux"
    appName: $(appName)
    package: "$(System.DefaultWorkingDirectory)/**/*.zip" #$(System.ArtifactsDirectory) alternative
    runtimeStack: "PYTHON|3.8"
    # Only required for deployment to slot
    #resourceGroupName: $(azureRgName)
    #slotName: $(slot)
